CREATE TABLE Users (
  Id INT PRIMARY KEY IDENTITY(1,1),
  CPF NVARCHAR(255) NOT NULL,
  NomeMae NVARCHAR(255) NOT NULL,
  NomeCrianca NVARCHAR(255) NOT NULL,
  DataCadastro DATETIME DEFAULT GETDATE()
);
